apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-test-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-test
  template:
    metadata:
      labels:
        app: proxy-test
    spec:
      containers:
      - name: nginx
        image: quay.io/bitnami/nginx:latest # 외부 이미지를 가져오는지 테스트
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-test-svc
spec:
  selector:
    app: proxy-test
  ports:
  - port: 80
    targetPort: 8080
